FROM apache/apisix:3.11.0-debian

USER root

# Install development tools and libraries
RUN apt-get update && \
    apt-get install -y \
        gcc \
        make \
        git \
        libssl-dev \
        libyaml-dev \
        wget \
        curl \
        unzip \
        sudo

# APISIX official luarocks installation script
RUN wget https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh && \
    sh linux-install-luarocks.sh && \
    rm linux-install-luarocks.sh

WORKDIR /usr/local/apisix

# Set up the environment to allow running make deps
# We don't run it here because we will mount the repo at runtime
